# Generated by Django 4.2.4 on 2023-08-15 19:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.TextField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appautenticacion.servicio')),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
    ]
